import type { SourceRecord } from "./model";
const checked = "2026-10-03";
export const sources: SourceRecord[] = [
  {
    id: "krakow-population",
    title: "Kraków in numbers — municipal population, 2024",
    publisher: "City of Kraków / Statistics Poland",
    url: "https://strategia.krakow.pl/getHtml?dok_id=253604",
    published: "2024 reference year; city statistics directory",
    checked: "2026-10-03",
    kind: "Municipal source",
  },
  {
    id: "helsinki-population",
    title: "Helsinki population at the end of 2024",
    publisher: "City of Helsinki / Statistics Finland",
    url: "https://www.hel.fi/en/news/population-of-helsinki-684000-at-the-turn-of-the-year-population-growth-almost-on-par-with-previous",
    published: "11 April 2025; 2024 reference year",
    checked: "2026-10-03",
    kind: "Municipal source",
  },
  {
    id: "krakow-plan",
    title: "Adaptacja Krakowa do zmian klimatu",
    publisher: "City of Kraków",
    url: "https://krakow.pl/getHtml?dok_id=290038",
    published: "Plan adopted 2020; actions updated 2023",
    checked,
    kind: "Municipal source",
  },
  {
    id: "krakow-heat",
    title: "Jak zielona infrastruktura może ochłodzić miasto",
    publisher: "City of Kraków",
    url: "https://krakow.pl/aktualnosci/293970,2163,komunikat,jak_zielona_infrastruktura_moze_ochlodzic_miasto.html",
    published: "28 April 2025",
    checked,
    kind: "Municipal source",
  },
  {
    id: "krakow-library",
    title: "Filie Biblioteki Kraków",
    publisher: "Kraków Public Information Bulletin",
    url: "https://bip.krakow.pl/?dok_id=83400",
    published: "Branch directory; checked 3 October 2026",
    checked,
    kind: "Municipal source",
  },
  {
    id: "krakow-gardens",
    title: "Ogrody Krakowian — 2026 inventory",
    publisher: "Kraków Municipal Greenery Authority (ZZM)",
    url: "https://zzm.krakow.pl/images/pliki/PLIKI%20PDF/Ogrody%20Krakowian_2026.pdf",
    published: "2026 inventory",
    checked,
    kind: "Municipal source",
  },
  {
    id: "barcelona-shelters",
    title: "More climate shelters to offer protection from the heat",
    publisher: "Barcelona City Council",
    url: "https://ajuntament.barcelona.cat/agenda2030/en/actualitat/creix-la-xarxa-de-refugis-climatics-per-protegir-se-de-la-calor-1524129",
    published: "4 June 2025",
    checked,
    kind: "Municipal source",
  },
  {
    id: "paris-oasis",
    title: "Les cours oasis",
    publisher: "City of Paris",
    url: "https://www.paris.fr/pages/les-cours-oasis-7389",
    published: "Updated 15 January 2025; count refers to 2023",
    checked,
    kind: "Municipal source",
  },
  {
    id: "paris-study",
    title:
      "Spatial Microclimatic Characterization of a Parisian “Oasis” Schoolyard",
    publisher: "Karam et al. — COBEE proceedings / arXiv",
    url: "https://arxiv.org/abs/2408.07284",
    published: "2023 proceedings; manuscript posted 29 July 2024",
    checked,
    kind: "Research",
  },
  {
    id: "medellin-corridors",
    title: "Climate Week 2026: Medellín’s green corridor network",
    publisher: "Alcaldía de Medellín",
    url: "https://www.medellin.gov.co/es/sala-de-prensa/noticias/en-la-climate-week-2026-medellin-sera-referente-global-de-sostenibilidad-urbana-con-su-red-de-corredores-verdes/",
    published: "20 September 2026",
    checked,
    kind: "Municipal source",
  },
  {
    id: "singapore-bishan",
    title: "Kallang River at Bishan–Ang Mo Kio Park",
    publisher: "PUB, Singapore’s National Water Agency",
    url: "https://www.pub.gov.sg/Public/Places-of-Interest/Our-Reservoirs-and-Waterways/Bishan-Ang-Mo-Kio-Park",
    published: "Project page; no publication date displayed",
    checked,
    kind: "Public agency",
  },
  {
    id: "singapore-guide",
    title: "ABC Waters Design Guidelines — Bishan–Ang Mo Kio case study",
    publisher: "PUB, Singapore’s National Water Agency",
    url: "https://www.pub.gov.sg/-/media/PUB/PDF/ABC_DG_2014.pdf",
    published: "2014 guidelines; project completed March 2012",
    checked,
    kind: "Public agency",
  },
  {
    id: "imgw",
    title: "Latest SYNOP report — Kraków station 12566",
    publisher: "IMGW-PIB",
    url: "https://danepubliczne.imgw.pl/api/data/synop/station/krakow",
    published: "Fetched on demand; observation time supplied in the response",
    checked,
    kind: "Live data",
  },
  {
    id: "imgw-docs",
    title: "Public meteorological data API",
    publisher: "IMGW-PIB",
    url: "https://dane.imgw.pl/apiinfo",
    published: "API documentation",
    checked,
    kind: "Live data",
  },
  {
    id: "forecast",
    title: "Weather forecast API",
    publisher: "Open-Meteo — CC BY 4.0",
    url: "https://open-meteo.com/en/docs",
    published: "Numerical weather model data; refreshed on demand",
    checked,
    kind: "Live data",
  },
  {
    id: "world-map",
    title: "Natural Earth world atlas, 1:110m",
    publisher: "Natural Earth / topojson world-atlas",
    url: "https://github.com/topojson/world-atlas",
    published: "world-atlas 2.0.2; Natural Earth public-domain geography",
    checked,
    kind: "Map data",
  },
  {
    id: "helsinki-info",
    title: "Helsinki-info, Central Library Oodi",
    publisher: "City of Helsinki",
    url: "https://www.hel.fi/en/decision-making/contact-us/helsinki-info/contact-information",
    published: "Service directory; checked 3 October 2026",
    checked,
    kind: "Municipal source",
  },
  {
    id: "urbact-transfer",
    title: "How to transfer urban good practice",
    publisher: "URBACT",
    url: "https://urbact.eu/news/how-transfer-urban-good-practice-lessons-urbact-study",
    published: "Transfer study guidance",
    checked,
    kind: "Public agency",
  },
  {
    id: "oecd-innovation",
    title: "Enhancing Innovation Capacity in City Government",
    publisher: "OECD",
    url: "https://www.oecd.org/en/publications/enhancing-innovation-capacity-in-city-government_f10c96e5-en.html",
    published: "2019",
    checked,
    kind: "Research",
  },
  {
    id: "design-council",
    title: "Framework for Innovation",
    publisher: "Design Council",
    url: "https://www.designcouncil.org.uk/resources/framework-for-innovation/",
    published: "Framework guidance; checked 3 October 2026",
    checked,
    kind: "Research",
  },
];
export const getSource = (id: string) => sources.find((s) => s.id === id);
